version: '3.9'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  node:
    container_name: node
    build:
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - .:/usr/src
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000

  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env
    ports:
      - 5432:5432
